version: "3"

services:
  rest_api:
    build: .
    command: /start-reload.sh
    volumes:
      - ./app:/app
    ports:
      - "8000:80"
    depends_on:
      - redis

  redis:
    image: redis
  redis-commander:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=redis
      - PORT=8081
    ports:
      - "8081:8081"
    depends_on:
      - redis